add check command for scripts in `path`

diff --git a/path/amt b/path/amt
--- a/path/amt
+++ b/path/amt
@@ -1,3 +1,9 @@
 #!/bin/bash
 
+if ! [ -x "$(command -v alsamixer)" ]; then
+  echo 'Error: alsamixer is not installed.' >&2
+  exit 1
+fi
+
+
 alacritty -e alsamixer
diff --git a/path/cfgwifi b/path/cfgwifi
--- a/path/cfgwifi
+++ b/path/cfgwifi
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+if ! [ -x "$(command -v nmcli)" ]; then
+  echo 'Error: nmcli  is not installed.' >&2
+  exit 1
+fi
+
+if ! [ -x "$(command -v nmtui)" ]; then
+  echo 'Error: nmtui is not installed.' >&2
+  exit 1
+fi
+
 nmcli dev wifi rescan
 # rescan the surrounding
 
diff --git a/path/gshot b/path/gshot
--- a/path/gshot
+++ b/path/gshot
@@ -2,6 +2,17 @@
 
 # runnable grim (screengrim) should be installed and added to path
 
+if ! [ -x "$(command -v grim)" ]; then
+  echo 'Error: grim is not installed.' >&2
+  exit 1
+fi
+
+if ! [ -x "$(command -v slurp)" ]; then
+  echo 'Error: slurp is not installed.' >&2
+  exit 1
+fi
+
+mkdir -p ~/Pictures/GCaptures
 FILENAME="screenshot-`date +%F-%T`"
 grim -g "$(slurp)" ~/Pictures/GCaptures/$FILENAME.png
 
diff --git a/path/lolfetch b/path/lolfetch
--- a/path/lolfetch
+++ b/path/lolfetch
@@ -1,3 +1,9 @@
 #!/bin/bash
 
+if ! [ -x "$(command -v lolcat)" ]; then
+  echo 'Error: lolcat is not installed.' >&2
+  exit 1
+fi
+
+
 neofetch | lolcat -h 0.90 -v 0.70
